# Generated by Django 4.0.1 on 2022-02-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='fun', max_length=255),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
