# Generated by Django 4.0.1 on 2022-02-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_newsstory_category_newsstory_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('PROGRAM', 'Program'), ('ANNOUNCEMENTS', 'Announcements')], default='news', max_length=200),
        ),
    ]
