# Generated by Django 4.0.1 on 2022-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_delete_category_alter_newsstory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(choices=[('FUN', 'Fun'), ('MUSIC', 'Music'), ('MOVIES', 'Movies'), ('EDUCATION', 'Education'), ('SCIENCE', 'Science'), ('TECHNOLOGY', 'Technology'), ('ANIMALS', 'Animals'), ('FOOD', 'Food')], default='news', max_length=200),
        ),
    ]
