# Generated by Django 4.0.1 on 2022-02-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsstory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(blank=True, help_text='(Copy Image Address)'),
        ),
    ]
